site_name: WordPress.wasm
theme:
    name: readthedocs

repo_url: https://github.com/WordPress/wordpress-wasm
edit_uri: blob/trunk/docs/

nav:
    - Overview: index.md
    - Using PHP in Javascript: using-php-in-javascript.md
    - Using PHP in the browser: using-php-in-the-browser.md
    - Using WordPress in the browser: using-wordpress-in-the-browser.md
    - API Reference:
          - php-wasm Reference: api/php-wasm.md
          - php-wasm-browser Reference: api/php-wasm-browser.md
          - wordpress-wasm Reference: api/wordpress-wasm.md

# markdown_extensions:
#     - meta
#     - toc

hooks: ['docs_hooks.py']
